dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.0.5
  shared_preferences: ^2.0.15
  firebase_core: ^3.8.1
  firebase_auth:^5.3.3
  cloud_firestore: ^5.2.2
  image_picker:^1.1.2
  swipe_cards: ^2.0.0+1
  

